// proto/sync/sync.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/sync/sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry - полная запись (с данными)
type Entry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags      []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	DataType  string                 `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // "login_password", "text", "binary", "bank_card"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version   int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	// Данные в зависимости от типа (oneof)
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Entry_LoginData
	//	*Entry_TextData
	//	*Entry_BinaryData
	//	*Entry_CardData
	Data          isEntry_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Entry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetData() isEntry_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entry) GetLoginData() *LoginPasswordData {
	if x != nil {
		if x, ok := x.Data.(*Entry_LoginData); ok {
			return x.LoginData
		}
	}
	return nil
}

func (x *Entry) GetTextData() *TextData {
	if x != nil {
		if x, ok := x.Data.(*Entry_TextData); ok {
			return x.TextData
		}
	}
	return nil
}

func (x *Entry) GetBinaryData() *BinaryData {
	if x != nil {
		if x, ok := x.Data.(*Entry_BinaryData); ok {
			return x.BinaryData
		}
	}
	return nil
}

func (x *Entry) GetCardData() *BankCardData {
	if x != nil {
		if x, ok := x.Data.(*Entry_CardData); ok {
			return x.CardData
		}
	}
	return nil
}

type isEntry_Data interface {
	isEntry_Data()
}

type Entry_LoginData struct {
	LoginData *LoginPasswordData `protobuf:"bytes,9,opt,name=login_data,json=loginData,proto3,oneof"`
}

type Entry_TextData struct {
	TextData *TextData `protobuf:"bytes,10,opt,name=text_data,json=textData,proto3,oneof"`
}

type Entry_BinaryData struct {
	BinaryData *BinaryData `protobuf:"bytes,11,opt,name=binary_data,json=binaryData,proto3,oneof"`
}

type Entry_CardData struct {
	CardData *BankCardData `protobuf:"bytes,12,opt,name=card_data,json=cardData,proto3,oneof"`
}

func (*Entry_LoginData) isEntry_Data() {}

func (*Entry_TextData) isEntry_Data() {}

func (*Entry_BinaryData) isEntry_Data() {}

func (*Entry_CardData) isEntry_Data() {}

// EntryMeta - метаданные записи (только для сравнения)
type EntryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	SyncedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryMeta) Reset() {
	*x = EntryMeta{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryMeta) ProtoMessage() {}

func (x *EntryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryMeta.ProtoReflect.Descriptor instead.
func (*EntryMeta) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *EntryMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntryMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EntryMeta) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *EntryMeta) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

func (x *EntryMeta) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// LoginPasswordData - данные логина/пароля
type LoginPasswordData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // зашифровано
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginPasswordData) Reset() {
	*x = LoginPasswordData{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPasswordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPasswordData) ProtoMessage() {}

func (x *LoginPasswordData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPasswordData.ProtoReflect.Descriptor instead.
func (*LoginPasswordData) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *LoginPasswordData) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginPasswordData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginPasswordData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LoginPasswordData) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// TextData - текстовые данные
type TextData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // зашифровано
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`   // "plain", "markdown", "html"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextData) Reset() {
	*x = TextData{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextData) ProtoMessage() {}

func (x *TextData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextData.ProtoReflect.Descriptor instead.
func (*TextData) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *TextData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// BinaryData - бинарные данные
type BinaryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // зашифровано
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryData) Reset() {
	*x = BinaryData{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryData) ProtoMessage() {}

func (x *BinaryData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryData.ProtoReflect.Descriptor instead.
func (*BinaryData) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *BinaryData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BinaryData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BinaryData) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *BinaryData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *BinaryData) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// BankCardData - данные банковской карты
type BankCardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"` // зашифровано
	CardHolder    string                 `protobuf:"bytes,2,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	ExpiryMonth   int32                  `protobuf:"varint,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    int32                  `protobuf:"varint,4,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"` // зашифровано
	CardType      string                 `protobuf:"bytes,6,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	BankName      string                 `protobuf:"bytes,7,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardData) Reset() {
	*x = BankCardData{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardData) ProtoMessage() {}

func (x *BankCardData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardData.ProtoReflect.Descriptor instead.
func (*BankCardData) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *BankCardData) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *BankCardData) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *BankCardData) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *BankCardData) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

func (x *BankCardData) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *BankCardData) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *BankCardData) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

// SyncRequest - запрос на синхронизацию
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncRequest_Snapshot
	//	*SyncRequest_Entry
	//	*SyncRequest_Ack
	Payload       isSyncRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetPayload() isSyncRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncRequest) GetSnapshot() *ClientSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *SyncRequest) GetEntry() *Entry {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *SyncRequest) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isSyncRequest_Payload interface {
	isSyncRequest_Payload()
}

type SyncRequest_Snapshot struct {
	Snapshot *ClientSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // первый запрос (метаданные всех записей)
}

type SyncRequest_Entry struct {
	Entry *Entry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"` // отправка полной записи (для need_from_client)
}

type SyncRequest_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"` // подтверждение получения инструкций
}

func (*SyncRequest_Snapshot) isSyncRequest_Payload() {}

func (*SyncRequest_Entry) isSyncRequest_Payload() {}

func (*SyncRequest_Ack) isSyncRequest_Payload() {}

// ClientSnapshot - слепок состояния клиента (первый запрос)
type ClientSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metas         []*EntryMeta           `protobuf:"bytes,2,rep,name=metas,proto3" json:"metas,omitempty"` // метаданные ВСЕХ записей клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSnapshot) Reset() {
	*x = ClientSnapshot{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSnapshot) ProtoMessage() {}

func (x *ClientSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSnapshot.ProtoReflect.Descriptor instead.
func (*ClientSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{7}
}

func (x *ClientSnapshot) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientSnapshot) GetMetas() []*EntryMeta {
	if x != nil {
		return x.Metas
	}
	return nil
}

// Ack - подтверждение получения инструкций
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // подтверждение готовности получить записи
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// SyncResponse - ответ на синхронизацию
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncResponse_Instructions
	//	*SyncResponse_Entry
	//	*SyncResponse_Complete
	Payload       isSyncResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{9}
}

func (x *SyncResponse) GetPayload() isSyncResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncResponse) GetInstructions() *SyncInstructions {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Instructions); ok {
			return x.Instructions
		}
	}
	return nil
}

func (x *SyncResponse) GetEntry() *Entry {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *SyncResponse) GetComplete() *SyncComplete {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isSyncResponse_Payload interface {
	isSyncResponse_Payload()
}

type SyncResponse_Instructions struct {
	Instructions *SyncInstructions `protobuf:"bytes,1,opt,name=instructions,proto3,oneof"` // инструкции для клиента
}

type SyncResponse_Entry struct {
	Entry *Entry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"` // потоковая передача записи (для need_download)
}

type SyncResponse_Complete struct {
	Complete *SyncComplete `protobuf:"bytes,3,opt,name=complete,proto3,oneof"` // завершение синхронизации
}

func (*SyncResponse_Instructions) isSyncResponse_Payload() {}

func (*SyncResponse_Entry) isSyncResponse_Payload() {}

func (*SyncResponse_Complete) isSyncResponse_Payload() {}

// SyncInstructions - инструкции для клиента (первый ответ)
type SyncInstructions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NeedDownload   []string               `protobuf:"bytes,1,rep,name=need_download,json=needDownload,proto3" json:"need_download,omitempty"`         // ID записей, которые нужно скачать (сервер новее или нет у клиента)
	NeedDelete     []string               `protobuf:"bytes,2,rep,name=need_delete,json=needDelete,proto3" json:"need_delete,omitempty"`               // ID записей, которые нужно удалить (нет на сервере)
	NeedFromClient []string               `protobuf:"bytes,3,rep,name=need_from_client,json=needFromClient,proto3" json:"need_from_client,omitempty"` // ID записей, которые клиент должен отправить (клиент новее или нет на сервере)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncInstructions) Reset() {
	*x = SyncInstructions{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInstructions) ProtoMessage() {}

func (x *SyncInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInstructions.ProtoReflect.Descriptor instead.
func (*SyncInstructions) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{10}
}

func (x *SyncInstructions) GetNeedDownload() []string {
	if x != nil {
		return x.NeedDownload
	}
	return nil
}

func (x *SyncInstructions) GetNeedDelete() []string {
	if x != nil {
		return x.NeedDelete
	}
	return nil
}

func (x *SyncInstructions) GetNeedFromClient() []string {
	if x != nil {
		return x.NeedFromClient
	}
	return nil
}

// SyncComplete - завершение синхронизации
type SyncComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"` // количество синхронизированных записей
	SyncVersion   int64                  `protobuf:"varint,2,opt,name=sync_version,json=syncVersion,proto3" json:"sync_version,omitempty"` // версия синхронизации (для будущих оптимизаций)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncComplete) Reset() {
	*x = SyncComplete{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncComplete) ProtoMessage() {}

func (x *SyncComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncComplete.ProtoReflect.Descriptor instead.
func (*SyncComplete) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{11}
}

func (x *SyncComplete) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncComplete) GetSyncVersion() int64 {
	if x != nil {
		return x.SyncVersion
	}
	return 0
}

var File_internal_proto_sync_sync_proto protoreflect.FileDescriptor

const file_internal_proto_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/sync/sync.proto\x12\x04sync\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x03\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tdata_type\x18\x05 \x01(\tR\bdataType\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x128\n" +
	"\n" +
	"login_data\x18\t \x01(\v2\x17.sync.LoginPasswordDataH\x00R\tloginData\x12-\n" +
	"\ttext_data\x18\n" +
	" \x01(\v2\x0e.sync.TextDataH\x00R\btextData\x123\n" +
	"\vbinary_data\x18\v \x01(\v2\x10.sync.BinaryDataH\x00R\n" +
	"binaryData\x121\n" +
	"\tcard_data\x18\f \x01(\v2\x12.sync.BankCardDataH\x00R\bcardDataB\x06\n" +
	"\x04data\"\xe4\x01\n" +
	"\tEntryMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x127\n" +
	"\tsynced_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"m\n" +
	"\x11LoginPasswordData\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"<\n" +
	"\bTextData\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x8f\x01\n" +
	"\n" +
	"BinaryData\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"\xe0\x01\n" +
	"\fBankCardData\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x1f\n" +
	"\vcard_holder\x18\x02 \x01(\tR\n" +
	"cardHolder\x12!\n" +
	"\fexpiry_month\x18\x03 \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x04 \x01(\x05R\n" +
	"expiryYear\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x1b\n" +
	"\tcard_type\x18\x06 \x01(\tR\bcardType\x12\x1b\n" +
	"\tbank_name\x18\a \x01(\tR\bbankName\"\x90\x01\n" +
	"\vSyncRequest\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x14.sync.ClientSnapshotH\x00R\bsnapshot\x12#\n" +
	"\x05entry\x18\x02 \x01(\v2\v.sync.EntryH\x00R\x05entry\x12\x1d\n" +
	"\x03ack\x18\x03 \x01(\v2\t.sync.AckH\x00R\x03ackB\t\n" +
	"\apayload\"T\n" +
	"\x0eClientSnapshot\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x05metas\x18\x02 \x03(\v2\x0f.sync.EntryMetaR\x05metas\"\x1b\n" +
	"\x03Ack\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\xae\x01\n" +
	"\fSyncResponse\x12<\n" +
	"\finstructions\x18\x01 \x01(\v2\x16.sync.SyncInstructionsH\x00R\finstructions\x12#\n" +
	"\x05entry\x18\x02 \x01(\v2\v.sync.EntryH\x00R\x05entry\x120\n" +
	"\bcomplete\x18\x03 \x01(\v2\x12.sync.SyncCompleteH\x00R\bcompleteB\t\n" +
	"\apayload\"\x82\x01\n" +
	"\x10SyncInstructions\x12#\n" +
	"\rneed_download\x18\x01 \x03(\tR\fneedDownload\x12\x1f\n" +
	"\vneed_delete\x18\x02 \x03(\tR\n" +
	"needDelete\x12(\n" +
	"\x10need_from_client\x18\x03 \x03(\tR\x0eneedFromClient\"T\n" +
	"\fSyncComplete\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12!\n" +
	"\fsync_version\x18\x02 \x01(\x03R\vsyncVersion2@\n" +
	"\vSyncService\x121\n" +
	"\x04Sync\x12\x11.sync.SyncRequest\x1a\x12.sync.SyncResponse(\x010\x01B3Z1github.com/Ko4etov/gophkeeper/internal/proto/syncb\x06proto3"

var (
	file_internal_proto_sync_sync_proto_rawDescOnce sync.Once
	file_internal_proto_sync_sync_proto_rawDescData []byte
)

func file_internal_proto_sync_sync_proto_rawDescGZIP() []byte {
	file_internal_proto_sync_sync_proto_rawDescOnce.Do(func() {
		file_internal_proto_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sync_sync_proto_rawDesc), len(file_internal_proto_sync_sync_proto_rawDesc)))
	})
	return file_internal_proto_sync_sync_proto_rawDescData
}

var file_internal_proto_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_sync_sync_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: sync.Entry
	(*EntryMeta)(nil),             // 1: sync.EntryMeta
	(*LoginPasswordData)(nil),     // 2: sync.LoginPasswordData
	(*TextData)(nil),              // 3: sync.TextData
	(*BinaryData)(nil),            // 4: sync.BinaryData
	(*BankCardData)(nil),          // 5: sync.BankCardData
	(*SyncRequest)(nil),           // 6: sync.SyncRequest
	(*ClientSnapshot)(nil),        // 7: sync.ClientSnapshot
	(*Ack)(nil),                   // 8: sync.Ack
	(*SyncResponse)(nil),          // 9: sync.SyncResponse
	(*SyncInstructions)(nil),      // 10: sync.SyncInstructions
	(*SyncComplete)(nil),          // 11: sync.SyncComplete
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_internal_proto_sync_sync_proto_depIdxs = []int32{
	12, // 0: sync.Entry.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: sync.Entry.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: sync.Entry.login_data:type_name -> sync.LoginPasswordData
	3,  // 3: sync.Entry.text_data:type_name -> sync.TextData
	4,  // 4: sync.Entry.binary_data:type_name -> sync.BinaryData
	5,  // 5: sync.Entry.card_data:type_name -> sync.BankCardData
	12, // 6: sync.EntryMeta.updated_at:type_name -> google.protobuf.Timestamp
	12, // 7: sync.EntryMeta.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 8: sync.EntryMeta.synced_at:type_name -> google.protobuf.Timestamp
	7,  // 9: sync.SyncRequest.snapshot:type_name -> sync.ClientSnapshot
	0,  // 10: sync.SyncRequest.entry:type_name -> sync.Entry
	8,  // 11: sync.SyncRequest.ack:type_name -> sync.Ack
	1,  // 12: sync.ClientSnapshot.metas:type_name -> sync.EntryMeta
	10, // 13: sync.SyncResponse.instructions:type_name -> sync.SyncInstructions
	0,  // 14: sync.SyncResponse.entry:type_name -> sync.Entry
	11, // 15: sync.SyncResponse.complete:type_name -> sync.SyncComplete
	6,  // 16: sync.SyncService.Sync:input_type -> sync.SyncRequest
	9,  // 17: sync.SyncService.Sync:output_type -> sync.SyncResponse
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_proto_sync_sync_proto_init() }
func file_internal_proto_sync_sync_proto_init() {
	if File_internal_proto_sync_sync_proto != nil {
		return
	}
	file_internal_proto_sync_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*Entry_LoginData)(nil),
		(*Entry_TextData)(nil),
		(*Entry_BinaryData)(nil),
		(*Entry_CardData)(nil),
	}
	file_internal_proto_sync_sync_proto_msgTypes[6].OneofWrappers = []any{
		(*SyncRequest_Snapshot)(nil),
		(*SyncRequest_Entry)(nil),
		(*SyncRequest_Ack)(nil),
	}
	file_internal_proto_sync_sync_proto_msgTypes[9].OneofWrappers = []any{
		(*SyncResponse_Instructions)(nil),
		(*SyncResponse_Entry)(nil),
		(*SyncResponse_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sync_sync_proto_rawDesc), len(file_internal_proto_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_sync_sync_proto_goTypes,
		DependencyIndexes: file_internal_proto_sync_sync_proto_depIdxs,
		MessageInfos:      file_internal_proto_sync_sync_proto_msgTypes,
	}.Build()
	File_internal_proto_sync_sync_proto = out.File
	file_internal_proto_sync_sync_proto_goTypes = nil
	file_internal_proto_sync_sync_proto_depIdxs = nil
}
