// proto/sync/sync.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/sync/sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry - полная запись (с данными)
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	DataType      string                 `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // "login_password", "text", "binary", "bank_card"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	EncryptedData string                 `protobuf:"bytes,9,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Entry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

// EntryMeta - метаданные записи (только для сравнения)
type EntryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	SyncedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryMeta) Reset() {
	*x = EntryMeta{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryMeta) ProtoMessage() {}

func (x *EntryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryMeta.ProtoReflect.Descriptor instead.
func (*EntryMeta) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *EntryMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntryMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EntryMeta) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *EntryMeta) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

func (x *EntryMeta) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EntryMeta) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// SyncRequest - запрос на синхронизацию
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncRequest_Snapshot
	//	*SyncRequest_Entry
	//	*SyncRequest_Ack
	Payload       isSyncRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetPayload() isSyncRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncRequest) GetSnapshot() *ClientSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *SyncRequest) GetEntry() *Entry {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *SyncRequest) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isSyncRequest_Payload interface {
	isSyncRequest_Payload()
}

type SyncRequest_Snapshot struct {
	Snapshot *ClientSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // первый запрос (метаданные всех записей)
}

type SyncRequest_Entry struct {
	Entry *Entry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"` // отправка полной записи (для need_from_client)
}

type SyncRequest_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"` // подтверждение получения инструкций
}

func (*SyncRequest_Snapshot) isSyncRequest_Payload() {}

func (*SyncRequest_Entry) isSyncRequest_Payload() {}

func (*SyncRequest_Ack) isSyncRequest_Payload() {}

// ClientSnapshot - слепок состояния клиента (первый запрос)
type ClientSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metas         []*EntryMeta           `protobuf:"bytes,2,rep,name=metas,proto3" json:"metas,omitempty"` // метаданные ВСЕХ записей клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSnapshot) Reset() {
	*x = ClientSnapshot{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSnapshot) ProtoMessage() {}

func (x *ClientSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSnapshot.ProtoReflect.Descriptor instead.
func (*ClientSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSnapshot) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientSnapshot) GetMetas() []*EntryMeta {
	if x != nil {
		return x.Metas
	}
	return nil
}

// Ack - подтверждение получения инструкций
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// SyncResponse - ответ на синхронизацию
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncResponse_Instructions
	//	*SyncResponse_Entry
	//	*SyncResponse_Complete
	Payload       isSyncResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetPayload() isSyncResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncResponse) GetInstructions() *SyncInstructions {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Instructions); ok {
			return x.Instructions
		}
	}
	return nil
}

func (x *SyncResponse) GetEntry() *Entry {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *SyncResponse) GetComplete() *SyncComplete {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isSyncResponse_Payload interface {
	isSyncResponse_Payload()
}

type SyncResponse_Instructions struct {
	Instructions *SyncInstructions `protobuf:"bytes,1,opt,name=instructions,proto3,oneof"` // инструкции для клиента
}

type SyncResponse_Entry struct {
	Entry *Entry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"` // потоковая передача записи (для need_download)
}

type SyncResponse_Complete struct {
	Complete *SyncComplete `protobuf:"bytes,3,opt,name=complete,proto3,oneof"` // завершение синхронизации
}

func (*SyncResponse_Instructions) isSyncResponse_Payload() {}

func (*SyncResponse_Entry) isSyncResponse_Payload() {}

func (*SyncResponse_Complete) isSyncResponse_Payload() {}

// SyncInstructions - инструкции для клиента (первый ответ)
type SyncInstructions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NeedDownload   []string               `protobuf:"bytes,1,rep,name=need_download,json=needDownload,proto3" json:"need_download,omitempty"`         // ID записей, которые нужно скачать
	NeedDelete     []string               `protobuf:"bytes,2,rep,name=need_delete,json=needDelete,proto3" json:"need_delete,omitempty"`               // ID записей, которые нужно удалить
	NeedFromClient []string               `protobuf:"bytes,3,rep,name=need_from_client,json=needFromClient,proto3" json:"need_from_client,omitempty"` // ID записей, которые клиент должен отправить
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncInstructions) Reset() {
	*x = SyncInstructions{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInstructions) ProtoMessage() {}

func (x *SyncInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInstructions.ProtoReflect.Descriptor instead.
func (*SyncInstructions) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SyncInstructions) GetNeedDownload() []string {
	if x != nil {
		return x.NeedDownload
	}
	return nil
}

func (x *SyncInstructions) GetNeedDelete() []string {
	if x != nil {
		return x.NeedDelete
	}
	return nil
}

func (x *SyncInstructions) GetNeedFromClient() []string {
	if x != nil {
		return x.NeedFromClient
	}
	return nil
}

// SyncComplete - завершение синхронизации
type SyncComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	SyncVersion   int64                  `protobuf:"varint,2,opt,name=sync_version,json=syncVersion,proto3" json:"sync_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncComplete) Reset() {
	*x = SyncComplete{}
	mi := &file_internal_proto_sync_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncComplete) ProtoMessage() {}

func (x *SyncComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sync_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncComplete.ProtoReflect.Descriptor instead.
func (*SyncComplete) Descriptor() ([]byte, []int) {
	return file_internal_proto_sync_sync_proto_rawDescGZIP(), []int{7}
}

func (x *SyncComplete) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncComplete) GetSyncVersion() int64 {
	if x != nil {
		return x.SyncVersion
	}
	return 0
}

var File_internal_proto_sync_sync_proto protoreflect.FileDescriptor

const file_internal_proto_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/sync/sync.proto\x12\x04sync\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x02\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tdata_type\x18\x05 \x01(\tR\bdataType\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12%\n" +
	"\x0eencrypted_data\x18\t \x01(\tR\rencryptedData\"\x80\x02\n" +
	"\tEntryMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x127\n" +
	"\tsynced_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\"\x90\x01\n" +
	"\vSyncRequest\x122\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x14.sync.ClientSnapshotH\x00R\bsnapshot\x12#\n" +
	"\x05entry\x18\x02 \x01(\v2\v.sync.EntryH\x00R\x05entry\x12\x1d\n" +
	"\x03ack\x18\x03 \x01(\v2\t.sync.AckH\x00R\x03ackB\t\n" +
	"\apayload\"T\n" +
	"\x0eClientSnapshot\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x05metas\x18\x02 \x03(\v2\x0f.sync.EntryMetaR\x05metas\"\x1b\n" +
	"\x03Ack\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\xae\x01\n" +
	"\fSyncResponse\x12<\n" +
	"\finstructions\x18\x01 \x01(\v2\x16.sync.SyncInstructionsH\x00R\finstructions\x12#\n" +
	"\x05entry\x18\x02 \x01(\v2\v.sync.EntryH\x00R\x05entry\x120\n" +
	"\bcomplete\x18\x03 \x01(\v2\x12.sync.SyncCompleteH\x00R\bcompleteB\t\n" +
	"\apayload\"\x82\x01\n" +
	"\x10SyncInstructions\x12#\n" +
	"\rneed_download\x18\x01 \x03(\tR\fneedDownload\x12\x1f\n" +
	"\vneed_delete\x18\x02 \x03(\tR\n" +
	"needDelete\x12(\n" +
	"\x10need_from_client\x18\x03 \x03(\tR\x0eneedFromClient\"T\n" +
	"\fSyncComplete\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12!\n" +
	"\fsync_version\x18\x02 \x01(\x03R\vsyncVersion2@\n" +
	"\vSyncService\x121\n" +
	"\x04Sync\x12\x11.sync.SyncRequest\x1a\x12.sync.SyncResponse(\x010\x01B3Z1github.com/Ko4etov/gophkeeper/internal/proto/syncb\x06proto3"

var (
	file_internal_proto_sync_sync_proto_rawDescOnce sync.Once
	file_internal_proto_sync_sync_proto_rawDescData []byte
)

func file_internal_proto_sync_sync_proto_rawDescGZIP() []byte {
	file_internal_proto_sync_sync_proto_rawDescOnce.Do(func() {
		file_internal_proto_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sync_sync_proto_rawDesc), len(file_internal_proto_sync_sync_proto_rawDesc)))
	})
	return file_internal_proto_sync_sync_proto_rawDescData
}

var file_internal_proto_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_sync_sync_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: sync.Entry
	(*EntryMeta)(nil),             // 1: sync.EntryMeta
	(*SyncRequest)(nil),           // 2: sync.SyncRequest
	(*ClientSnapshot)(nil),        // 3: sync.ClientSnapshot
	(*Ack)(nil),                   // 4: sync.Ack
	(*SyncResponse)(nil),          // 5: sync.SyncResponse
	(*SyncInstructions)(nil),      // 6: sync.SyncInstructions
	(*SyncComplete)(nil),          // 7: sync.SyncComplete
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_internal_proto_sync_sync_proto_depIdxs = []int32{
	8,  // 0: sync.Entry.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: sync.Entry.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: sync.EntryMeta.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 3: sync.EntryMeta.deleted_at:type_name -> google.protobuf.Timestamp
	8,  // 4: sync.EntryMeta.synced_at:type_name -> google.protobuf.Timestamp
	3,  // 5: sync.SyncRequest.snapshot:type_name -> sync.ClientSnapshot
	0,  // 6: sync.SyncRequest.entry:type_name -> sync.Entry
	4,  // 7: sync.SyncRequest.ack:type_name -> sync.Ack
	1,  // 8: sync.ClientSnapshot.metas:type_name -> sync.EntryMeta
	6,  // 9: sync.SyncResponse.instructions:type_name -> sync.SyncInstructions
	0,  // 10: sync.SyncResponse.entry:type_name -> sync.Entry
	7,  // 11: sync.SyncResponse.complete:type_name -> sync.SyncComplete
	2,  // 12: sync.SyncService.Sync:input_type -> sync.SyncRequest
	5,  // 13: sync.SyncService.Sync:output_type -> sync.SyncResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_proto_sync_sync_proto_init() }
func file_internal_proto_sync_sync_proto_init() {
	if File_internal_proto_sync_sync_proto != nil {
		return
	}
	file_internal_proto_sync_sync_proto_msgTypes[2].OneofWrappers = []any{
		(*SyncRequest_Snapshot)(nil),
		(*SyncRequest_Entry)(nil),
		(*SyncRequest_Ack)(nil),
	}
	file_internal_proto_sync_sync_proto_msgTypes[5].OneofWrappers = []any{
		(*SyncResponse_Instructions)(nil),
		(*SyncResponse_Entry)(nil),
		(*SyncResponse_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sync_sync_proto_rawDesc), len(file_internal_proto_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_sync_sync_proto_goTypes,
		DependencyIndexes: file_internal_proto_sync_sync_proto_depIdxs,
		MessageInfos:      file_internal_proto_sync_sync_proto_msgTypes,
	}.Build()
	File_internal_proto_sync_sync_proto = out.File
	file_internal_proto_sync_sync_proto_goTypes = nil
	file_internal_proto_sync_sync_proto_depIdxs = nil
}
